[cursor]
style = "Block"

[font]
size = 15.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
# family = "Comic Code Ligatures"
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_padding = true
startup_mode = "Windowed"
title = "Alacritty"
opacity = 1.0
blur = false
option_as_alt = "Both"

[window.padding]
x = 10
y = 6

[general]
live_config_reload = true
working_directory = "None"
import = ["~/.config/alacritty/themes/themes/github_light.toml"]
